### PR TITLE
Remove C99 initializers from C++ code

### PR DESCRIPTION
**Pull request by sfiera**

### CODE REVIEW

**Comment by sfiera** [comment]
@orbea, does this address #310?

**Comment by orbea** [comment]
Yes, it now builds here with clang10, thanks!

**Comment by sfiera** [comment]
I changed it a little more, but I think it should still be fine. Sorry for the wait, one build failed and that was a larger problem to address.

**Comment by orbea** [comment]
Thanks, I can confirm it still fixes my issue.

**Pull request merged**
