### PR TITLE
Rely on installed binaries instead of bundling

### PR DESCRIPTION
**Pull request by sfiera**
Remove gn and ninja binaries from the build/lib submodule.

Packages to install them (on Mac and Debian-like systems) are now
provided external to Antares. ./configure directs the user on these
systems.

The main motivation here is for Antares on ARM (Raspberry Pi now, but
eventually Apple Silicon). Antares was already shipping six binaries in
each tarball ({gn,ninja} × {mac,linux,win}), and that would have
increased further to support {x86_64,arm,arm64}. Aside from that, Chrome
does not provide non-x86_64 binaries, so it would have been necessary to
build some ammount of support infrastructure anyway.

### CODE REVIEW

**Comment by sfiera** [comment]
Maintainers of Antares packages:
* @Mailaender This introduces a dep on gn, which appears to be in OpenSUSE already (gyp is no longer necessary).
* @orbea I believe this should be an improvement for you, as it looks like you already package [gn](https://slackbuilds.org/repository/14.2/development/gn/) for SlackBuilds.

I’m going to let this sit for a few days in case you have a chance to weigh in.

**Comment by orbea** [comment]
Sounds good to me, I already depend on the system versions of gn and ninja (Or samurai).

**Comment by Mailaender** [comment]
@kieltux is currently working on https://build.opensuse.org/package/show/home:Kieltux:branches:games/antares getting this to run with non-obsolete Python versions on @openSUSE.

**Comment by Kieltux** [comment]
Looks fine. Antares 0.91 build for openSUSE Tumbleweed.
```
[  100s] RPMLINT report:
[  100s] ===============
[  102s] antares.x86_64: W: position-independent-executable-suggested /usr/lib/antares/antares-glfw
[  102s] antares.x86_64: W: position-independent-executable-suggested /usr/lib/antares/antares-install-data
[  102s] This executable should be position independent (all binaries should).  Check
[  102s] that it is built with -fPIE/-fpie in compiler flags and -pie in linker flags.
[  102s] 
[  102s] 2 packages and 0 specfiles checked; 0 errors, 2 warnings.
[  102s] 
[  102s] ... creating baselibs
[  102s] ... saving statistics
[  102s] ... saving built packages
[  102s] RPMS/x86_64/antares-debuginfo-0.9.1-46.1.x86_64.rpm
[  102s] RPMS/x86_64/antares-0.9.1-46.1.x86_64.rpm
[  102s] SRPMS/antares-0.9.1-46.1.src.rpm
[  102s] OTHER/rpmlint.log
[  102s] OTHER/_statistics
```
I did have problems to build Antares 0.90 for openSUSE Tumbleweed (missing dependencies: python-gi).

**Comment by sfiera** [comment]
Just to be clear—this change is not in 0.9.1. The 0.9.1 distfile contains precompiled x86_64 gn and ninja binaries (three each, actually) and doesn’t depend on the system packages. After this change, Antares would use system-provided binaries and you could remove `ExclusiveArch: x86_64` (supporting [wherever gn is available](https://build.opensuse.org/package/show/network:chromium/gn)).

Aside: There are other changes between 0.9.1 and HEAD, most significantly the removal of the launcher (along with the python-{gi,gtk} deps but not python3). On Mac, a plugin now opens by double-clicking the plugin, or via drag-and-drop. On Linux, I assume this requires `Exec=/usr/games/antares %f` and `MimeTypes=application/x-antares-plugin`, with something to register the mime type ([maybe this](https://www.freedesktop.org/wiki/Specifications/AddingMIMETutor/)?). antares-glfw is also renamed to antares.

That’s a big enough change that it will probably be 0.10.0. I am also hoping to address #167 and #277 before then, and get Antares running on a Pi 0 (Pi 4 works as of this change).

**Comment by Kieltux** [comment]
Thank you for your clarification. I was a bit in hurry yesterday.

**Pull request merged**
